namespace SkolplattformenElevApi.Models.Internal.Login;


    // Autogenerated from answer to https://login.microsoftonline.com/common/GetCredentialType?mkt=en-US
    // CredentialType myDeserializedClass = JsonConvert.DeserializeObject<CredentialType>(myJsonResponse);
    internal class Credentials
    {
        //public int PrefCredential { get; set; }
        //public bool HasPassword { get; set; }
        //public object RemoteNgcParams { get; set; }
        //public object FidoParams { get; set; }
        //public object SasParams { get; set; }
        //public object CertAuthParams { get; set; }
        //public object GoogleParams { get; set; }
        //public object FacebookParams { get; set; }
        public string FederationRedirectUrl { get; set; }
    }

    //internal class EstsProperties
    //{
    //    public object UserTenantBranding { get; set; }
    //    public int DomainType { get; set; }
    //}

    internal class CredentialType
    {
        //public string Username { get; set; }
        //public string Display { get; set; }
        //public int IfExistsResult { get; set; }
        //public bool IsUnmanaged { get; set; }
        //public int ThrottleStatus { get; set; }
        public Credentials Credentials { get; set; }
        //public EstsProperties EstsProperties { get; set; }
        public string FlowToken { get; set; }
        public bool IsSignupDisallowed { get; set; }
        public string apiCanary { get; set; }
    }

    // ---- login.srf

  

    //internal class Desktopsso
    //{
    //    public string authenticatingmessage { get; set; }
    //}

    //internal class DesktopSsoConfig
    //{
    //    public bool isEdgeAnaheimAllowed { get; set; }
    //    public string iwaEndpointUrlFormat { get; set; }
    //    public string iwaSsoProbeUrlFormat { get; set; }
    //    public string iwaIFrameUrlFormat { get; set; }
    //    public int iwaRequestTimeoutInMs { get; set; }
    //    public bool startDesktopSsoOnPageLoad { get; set; }
    //    public int progressAnimationTimeout { get; set; }
    //    public bool isEdgeAllowed { get; set; }
    //    public string minDssoEdgeVersion { get; set; }
    //    public bool isSafariAllowed { get; set; }
    //    public string redirectUri { get; set; }
    //    public RedirectDssoErrorPostParams redirectDssoErrorPostParams { get; set; }
    //    public bool isIEAllowedForSsoProbe { get; set; }
    //    public string edgeRedirectUri { get; set; }
    //}


    //internal class Instr
    //{
    //    public string pageload { get; set; }
    //    public string dssostatus { get; set; }
    //}

    //internal class Loader
    //{
    //    public List<string> cdnRoots { get; set; }
    //    public bool logByThrowing { get; set; }
    //}

    //internal class Locale
    //{
    //    public string mkt { get; set; }
    //    public int lcid { get; set; }
    //}

    //internal class OAppCobranding
    //{
    //}

    //internal class Os
    //{
    //    public string name { get; set; }
    //    public string version { get; set; }
    //}

    //internal class RedirectDssoErrorPostParams
    //{
    //    public string error { get; set; }
    //    public string error_description { get; set; }
    //    public string state { get; set; }
    //}

internal class LoginSrfAnswer
{
    //public int iMaxStackForKnockoutAsyncComponents { get; set; }
    //public bool fShowButtons { get; set; }
    //public string urlCdn { get; set; }
    //public string urlDefaultFavicon { get; set; }
    //public string urlFooterTOU { get; set; }
    //public string urlFooterPrivacy { get; set; }
    //public string urlPost { get; set; }
    //public int iPawnIcon { get; set; }
    //public string sPOST_Username { get; set; }
    public string sFT { get; set; }

    //public string sFTName { get; set; }
    public string sCtx { get; set; }

    //public string sCanaryTokenName { get; set; }
    //public bool fEnableOneDSClientTelemetry { get; set; }
    //public string urlReportPageLoad { get; set; }
    //public object dynamicTenantBranding { get; set; }
    //public object staticTenantBranding { get; set; }
    //public OAppCobranding oAppCobranding { get; set; }
    //public int iBackgroundImage { get; set; }
    //public bool fApplicationInsightsEnabled { get; set; }
    //public int iApplicationInsightsEnabledPercentage { get; set; }
    //public string urlSetDebugMode { get; set; }
    //public bool fEnableCssAnimation { get; set; }
    //public bool fAllowGrayOutLightBox { get; set; }
    //public bool fIsRemoteNGCSupported { get; set; }
    //public DesktopSsoConfig desktopSsoConfig { get; set; }
    //public int iSessionPullType { get; set; }
    //public bool fUseSameSite { get; set; }
    //public int uiflavor { get; set; }
    //public bool fOfflineAccountVisible { get; set; }
    //public bool fEnableUserStateFix { get; set; }
    //public bool fShowAccessPassPeek { get; set; }
    //public bool fUpdateSessionPollingLogic { get; set; }
    //public bool fFloatTileMenu { get; set; }
    //public int scid { get; set; }
    //public int hpgact { get; set; }
    //public int hpgid { get; set; }
    //public string pgid { get; set; }
    //public string apiCanary { get; set; }
    public string canary { get; set; }

    //public string correlationId { get; set; }
    public string sessionId { get; set; }
    //public Locale locale { get; set; }
    //public int slMaxRetry { get; set; }
    //public bool slReportFailure { get; set; }
    //public Strings strings { get; set; }

    //public Urls urls { get; set; }


    //public bool fApplyAsciiRegexOnInput { get; set; }
    //public string country { get; set; }
    //public bool fBreakBrandingSigninString { get; set; }
    //public string urlNoCookies { get; set; }
    //public bool fTrimChromeBssoUrl { get; set; }
    //public int inlineMode { get; set; }
    //public bool fShowCopyDebugDetailsLink { get; set; }
}




